version: '3.8'

services:
  fastapi_app:
    build:
      context: ./app  # Indique que le Dockerfile est dans le dossier app
      dockerfile: Dockerfile  # Spécifie le nom du Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8001:8001"  # Port mis à jour

  nginx:
    image: nginx:latest
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs  # Volume pour les certificats SSL
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi_app
